### ISSUE TITLE
Les canards n'apparaissent plus (timer figé ?)

### ISSUE THREAD

**Issue by Dragorn421** [DuckHunt-discord/DHV2#32]
Salut !

Cet après midi j'ai remarqué avec un autre que les canards ont cessé d'apparaître dans le channel dédié au bot, donc je fais !help et l'autre !ping pour voir si le bot est en ligne, pas de problème.
Un !bang trouve un canard, et en effet d'après les derniers messages du bot un canard devrait être présent. Il s'agissait d'un supercanard et une fois tué plus aucun canard n'était là.

Les logs concernés https://pastebin.com/Gptr5wZm

Comme on le voit la limite est de 100 canards par jour donc ce n'était pas le problème, et le bot semble avoir arrêté d'envoyer des messages après 10:30 ce matin (16/06)

Je ne sais pas qui héberge le bot, je crois bien que c'est le bot "officiel" (vous) :) (son id 187636089073172481)

Ma théorie c'est qu'un timer quelconque a été stoppé ou a planté puisque que le canard ne semble pas avoir disparu après plusieurs heures et aucun n'est apparu.

**Comment by Dragorn421** [comment]
Et au moment où je post l'issue comme par magie un nouveau canard apparaît sur le channel après plus de 8 heures d'inactivité !

**Comment by Diagamma** [comment]
Yep ça a planté à cette heure effectivement, on sait pas trop pourquoi, mais le bot a été reboot et vu ton second message ça a l'air de fonctionner à nouveau.
