### ISSUE TITLE
!top types

### ISSUE THREAD

**Issue by sholan** [DuckHunt-discord/DHV2#6]
Hello,

I was thinking about the possibility of providing more with the !top command.

For instance : 

- [ ] "!top missed [n]" the top n players accounting for missed duck stat
- [ ] "!top ghost [n]" the top n players accounting for no duck shots
- [ ] "!top time [n]" the top n players accounting for minimal shot time
- [ ] "!top ratio [n]" the top n players accounting for exp/kills ratio

Maybe more data are accessible ... 

This is purely cosmetics ;)

**Comment by Heroesflorian** [comment]
I really like the idea of having an option to sort highscores not only by XP but also by # ducks killed, fastest kill time or best XP/kill ratio. 

Would suggest different argument order though, to not "break" (people used to) the existing version of the !top command... i.e. rather `!top [n] [sorting_criterion]` than the other way round.

**Comment by Diagamma** [comment]
This parameter has been added. It can be used the way @Heroesflorian suggested.
Currently, it only supports "exp", "killed" and "missed". I'll add more later (like the best time and the ratio), but if you really want a specific one ASAP, just tell me (without reopening the issue).
